### ISSUE TITLE
Which features should we demo?

### ISSUE THREAD

**Issue by GenevieveBuckley** [pyladiesmelbourne/ides-of-march#3]
@flyladyhawke suggests giving everyone a few common things to explain how to do in their IDE talk. This seems like a good idea, and should make it easier to compare IDEs.

The most popular features according to the 2018 Python Developers Survey were:

* version control
* code autocompletion
* code refactorings
* writing unit tests
* using virtual environments for Python projects
* SQL databases
* debugging
* code linting

Maybe we should pick a handful from this list?

**Comment by mareecarroll** [comment]
Depends on how long we get to talk each. I would be good to mention them all if time. How long do you think we should talk?

**Comment by GenevieveBuckley** [comment]
@pfctdayelise suggests:

> So this is how I imagine it working
> - We get a laptop and get all the IDEs installed on it
> - We check out a codebase onto the laptop and set up the virtualenv for it, check we can run tests and run the code through the command line
> - Each IDE demo should go through the following:

> 1. Open the codebase in the IDE (configure virtualenv if needed)
> 2. Open a file (say main.py), show syntax highlighting
> 3. Show code autocomplete
> 4. Refactoring - rename a variable
> 5. Jump to function/method definition
> 6. Show git blame for a file
> 7. Search in codebase
> 8. Run the code
> 9. Run the tests
> 10. Bonus feature (presenter's choice)

**Comment by mareecarroll** [comment]
@pfctdayelise @GenevieveBuckley I'm happy with this setup if you are. :)

**Comment by pfctdayelise** [comment]
Such organisation! thank you @mareecarroll and @GenevieveBuckley 💕💕

Which codebase to use is a good Q. Something that's simple to run or demo that has some pytest tests would be handy.

**Comment by mareecarroll** [comment]
@pfctdayelise @GenevieveBuckley 

My suggestion is https://github.com/redacted/XKCD-password-generator because it ticks the boxes of:

- [x] simple to run
- [x] has tests, which can be run with pytest
- [x] mandatory xkcd comic in a presentation! (bonus points because it isn't the correlation != causation one

I'll add the readme I've been writing to ensure I'm somewhat ready for the smackdown, in case it helps with the setup.

**Comment by mareecarroll** [comment]
@pfctdayelise @GenevieveBuckley 
see https://github.com/pyladiesmelbourne/ides-of-march/blob/master/vs-code-demo.md
